apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: activemq
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm/activemq
    repoURL: https://github.com/SergeyDz/argocd-education
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: activemq
  syncPolicy:
    # automated: {}
    syncOptions:
      - CreateNamespace=true